{% set name = "b4msa" %}
{% set version = "2.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/b4msa-{{ version }}.tar.gz
  sha256: 6ae8058e7ae0dd2064e570f079902d153b366ff40cb9cd3c77d240114c7e7b50

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - scikit-learn
  run:
    - python >=3.6
    - scikit-learn
    - microtc

test:
  imports:
    - b4msa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/b4msa/
  summary: A Baseline for Multilingual Sentiment Analysis
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
